### PR TITLE
Upgrade to latest release 0.94i

### PR DESCRIPTION
**Pull request by saraedum**

### CODE REVIEW

**Comment by saraedum** [comment]
@conda-forge-admin, please rerender.

**Comment by saraedum** [comment]
@isuruf Any chance we can switch to the upstream versioning scheme `0.94i` instead of `094i`?

**Comment by saraedum** [comment]
Hm…we're essentially at version 94 now:
```
>>> from conda.resolve import normalized_version
>>> A=normalized_version('094h')
>>> A.version
[[0], [94, 'h']]
>>> B=normalized_version('0.94i')
>>> B.version
[[0], [0], [94, 'i']]
```

**Comment by saraedum** [comment]
@conda-forge-admin, please rerender.

**Comment by saraedum** [comment]
@conda-forge-admin, please update circle

**Comment by saraedum** [comment]
@isuruf If you know some trick to get CircleCI back online that would be great :)

**Comment by isuruf** [comment]
@conda-forge-admin, please rerender

**Pull request merged**
